#!/usr/bin/env bash
# Build a local, commit-addressed lab package. CycloneDX identifiers and
# timestamps are generated by Trivy, so its SBOM is intentionally not claimed
# to be byte-for-byte reproducible; the sibling checksum binds this artifact.
set -euo pipefail
umask 022

fail() {
    printf '%s\n' "lab package build failed: $*" >&2
    exit 1
}

command -v realpath >/dev/null || fail 'realpath is required to validate artifact output paths'
command -v jq >/dev/null || fail 'jq is required to normalize and validate the CycloneDX SBOM'
repo_root=$(git rev-parse --show-toplevel)
repo_root=$(realpath -e -- "$repo_root")
[[ -d "$repo_root" && ! -L "$repo_root" ]] || fail 'repository root is not a real directory'
cd "$repo_root"

if [[ ${SDCMCP_ALLOW_DIRTY:-0} != 1 ]] && [[ -n $(git status --porcelain) ]]; then
    printf '%s\n' 'refusing to package a dirty tree (set SDCMCP_ALLOW_DIRTY=1 for development)' >&2
    exit 1
fi

trivy_version=$(trivy --version | sed -n 's/^Version: //p' | head -n 1)
[[ "$trivy_version" == 0.70.0 ]] || {
    printf '%s\n' "Trivy 0.70.0 is required; found ${trivy_version:-none}" >&2
    exit 1
}

git_commit=$(git rev-parse HEAD)
[[ "$git_commit" =~ ^[0-9a-f]{40}$ ]] || fail 'HEAD must resolve to a full lowercase Git commit'
git_sha12=${git_commit:0:12}
source_date_epoch=$(git show -s --format=%ct HEAD)
package_date=$(date -u -d "@$source_date_epoch" +%Y%m%d)
package_root="rustsdcmcp_0.1.0-lab.${package_date}.${git_sha12}_amd64"
repo_dist="$repo_root/dist"
if [[ -e "$repo_dist" || -L "$repo_dist" ]]; then
    [[ -d "$repo_dist" && ! -L "$repo_dist" ]] || fail "artifact root is not a real directory: $repo_dist"
else
    mkdir -m 0755 -- "$repo_dist"
fi
repo_dist=$(realpath -e -- "$repo_dist")
[[ "$repo_dist" == "$repo_root/dist" ]] || fail 'artifact root resolves outside the physical repository root'

dist_dir="$repo_dist/$git_commit"
if [[ -e "$dist_dir" || -L "$dist_dir" ]]; then
    [[ -d "$dist_dir" && ! -L "$dist_dir" ]] || fail "commit artifact directory is not a real directory: $dist_dir"
else
    mkdir -m 0755 -- "$dist_dir"
fi
dist_dir=$(realpath -e -- "$dist_dir")
[[ "$dist_dir" == "$repo_dist/$git_commit" && $(dirname -- "$dist_dir") == "$repo_dist" ]] \
    || fail 'commit artifact directory is not the immediate commit child of dist'

archive="$dist_dir/${package_root}.tar.gz"
checksum="${archive}.sha256"
validate_output_entries() {
    local entry type count=0
    declare -A allowed=(
        ["$(basename -- "$archive")"]=1
        ["$(basename -- "$checksum")"]=1
    )
    while IFS=$'\t' read -r entry type; do
        [[ -n "$entry" && "$type" == f && ${allowed[$entry]+yes} ]] \
            || fail "commit artifact directory contains an unsafe or unexpected entry: $dist_dir/$entry"
        [[ ! -L "$dist_dir/$entry" ]] || fail "commit artifact directory contains a symlink: $dist_dir/$entry"
        ((count += 1))
    done < <(find -P "$dist_dir" -mindepth 1 -maxdepth 1 -printf '%f\t%y\n')
    if [[ ${1:-allow-stale} == exact ]]; then
        [[ $count -eq 2 && -f "$archive" && ! -L "$archive" && -f "$checksum" && ! -L "$checksum" ]] \
            || fail "commit artifact directory must contain exactly the archive and checksum: $dist_dir"
    fi
}
validate_output_entries

rm -f -- "$archive" "$checksum"
artifact_complete=0
build_dir=
cleanup() {
    if [[ -n "$build_dir" ]]; then
        rm -rf -- "$build_dir"
    fi
    if [[ $artifact_complete != 1 ]]; then
        rm -f -- "$archive" "$checksum"
    fi
}

cargo build --release -p rustsdcmcp --locked

build_dir=$(mktemp -d)
trap cleanup EXIT
stage_dir="$build_dir/$package_root"
mkdir -p "$stage_dir/bin" "$stage_dir/config" "$stage_dir/packaging/lxc" \
    "$stage_dir/packaging/systemd" "$stage_dir/packaging/journald" "$stage_dir/docs"

install -m 0755 target/release/rustsdcmcp "$stage_dir/bin/rustsdcmcp"
# The source example is intentionally retained unchanged; the package carries
# the package-specific state location consumed by its installed service.
sed 's#/var/lib/sdcmcp/changeset-state.json#/var/lib/rustsdcmcp/changeset-state.json#' \
    examples/sdc.example.json >"$stage_dir/config/sdc.json.example"
install -m 0755 packaging/lxc/install.sh "$stage_dir/packaging/lxc/install.sh"
install -m 0644 packaging/systemd/rustsdcmcp.service "$stage_dir/packaging/systemd/rustsdcmcp.service"
install -m 0644 packaging/systemd/rustsdcmcp.sysusers "$stage_dir/packaging/systemd/rustsdcmcp.sysusers"
install -m 0644 packaging/systemd/rustsdcmcp.tmpfiles "$stage_dir/packaging/systemd/rustsdcmcp.tmpfiles"
install -m 0644 packaging/journald/mecmcp.conf "$stage_dir/packaging/journald/mecmcp.conf"
install -m 0644 README.md LICENSE SECURITY.md "$stage_dir/"
install -m 0644 docs/operations.md "$stage_dir/docs/operations.md"

glibc_floor=$(objdump -T "$stage_dir/bin/rustsdcmcp" \
    | { grep -oE 'GLIBC_[0-9]+(\.[0-9]+)+' || true; } \
    | sed 's/GLIBC_//' | sort -Vu | tail -n 1)
[[ -n "$glibc_floor" ]] || {
    printf '%s\n' 'could not determine GLIBC floor' >&2
    exit 1
}
rustc_metadata=$(rustc -vV | tr '\n' ' ' | sed 's/[[:space:]]*$//')
cat >"$stage_dir/BUILD-INFO" <<EOF
release_status=lab-only
version=0.1.0
git_commit=$git_commit
source_date_epoch=$source_date_epoch
target=x86_64-unknown-linux-gnu
mecmcp_ref=changeset-v0.3.7
glibc_floor=$glibc_floor
rustc=$rustc_metadata
EOF

# Skip every directory .gitignore already excludes, plus the two places a git
# worktree lands. A nested checkout carries its own Cargo.lock, which Trivy
# reports as a second copy of every dependency -- the SBOM assertions below
# then fail on duplicates that are not in the shipped artifact at all.
trivy filesystem --scanners vuln --format cyclonedx \
    --skip-dirs target,dist,.git,.worktrees,.claude \
    --output "$stage_dir/SBOM.cdx.json" "$repo_root"
sbom_tmp="$stage_dir/SBOM.cdx.json.tmp"
jq '.metadata.component.name = "rustsdcmcp"' "$stage_dir/SBOM.cdx.json" >"$sbom_tmp"
mv -- "$sbom_tmp" "$stage_dir/SBOM.cdx.json"
jq -e '
    .bomFormat == "CycloneDX"
    and (.metadata.component.name == "rustsdcmcp")
    and (.components | type == "array" and length > 0)
    and any(.components[]; .name == "serde")
    and (
        ([
            .components[]
            | select(.name? | strings | startswith("mecmcp-"))
            | [.name, .version]
        ] | sort)
        == [
            ["mecmcp-audit", "0.3.7"],
            ["mecmcp-auth", "0.3.7"],
            ["mecmcp-changeset", "0.3.7"],
            ["mecmcp-runtime", "0.3.7"],
            ["mecmcp-transport", "0.3.7"]
        ]
    )
    and (tostring | contains("changeset-v0.3.6") | not)
    and (tostring | contains("93ab63d7c2fad649112807378f92fcc26cce73c6") | not)
' "$stage_dir/SBOM.cdx.json" >/dev/null || {
    sbom_mecmcp=$(jq -r '
        [.components[]? | select(.name? | strings | startswith("mecmcp-")) | .name]
        | length
    ' "$stage_dir/SBOM.cdx.json" 2>/dev/null || printf '?')
    if [[ $sbom_mecmcp =~ ^[0-9]+$ ]] && ((sbom_mecmcp > 5)); then
        fail "normalized SBOM lists $sbom_mecmcp mecmcp components, expected 5; a nested checkout under the repo root was scanned as a second copy"
    fi
    fail 'normalized SBOM lacks required metadata or dependencies'
}
! grep -Fq -- "$repo_root" "$stage_dir/SBOM.cdx.json" \
    || fail 'SBOM contains an absolute repository or worktree path'
chmod 0644 "$stage_dir/SBOM.cdx.json"

(
    cd "$build_dir"
    find "$package_root" -print0 | LC_ALL=C sort -z \
        | tar --create --gzip --file="$archive" --format=posix --sort=name \
            --owner=0 --group=0 --numeric-owner \
            --mtime="@$source_date_epoch" \
            --pax-option=delete=atime,delete=ctime --no-recursion \
            --null --files-from=-
)
(
    cd "$dist_dir"
    sha256sum "$(basename -- "$archive")" >"$(basename -- "$checksum")"
    sha256sum -c "$(basename -- "$checksum")"
)
validate_output_entries exact
packaging/tests/package-smoke.sh "$archive"
artifact_complete=1
printf '%s\n' "built $archive"
