#!/usr/bin/env bash
# Build a local, commit-addressed lab package. CycloneDX identifiers and
# timestamps are generated by Trivy, so its SBOM is intentionally not claimed
# to be byte-for-byte reproducible; the sibling checksum binds this artifact.
set -euo pipefail
umask 022

repo_root=$(git rev-parse --show-toplevel)
cd "$repo_root"

if [[ ${SDCMCP_ALLOW_DIRTY:-0} != 1 ]] && [[ -n $(git status --porcelain) ]]; then
    printf '%s\n' 'refusing to package a dirty tree (set SDCMCP_ALLOW_DIRTY=1 for development)' >&2
    exit 1
fi

trivy_version=$(trivy --version | sed -n 's/^Version: //p' | head -n 1)
[[ "$trivy_version" == 0.70.0 ]] || {
    printf '%s\n' "Trivy 0.70.0 is required; found ${trivy_version:-none}" >&2
    exit 1
}

git_commit=$(git rev-parse HEAD)
git_sha12=${git_commit:0:12}
source_date_epoch=$(git show -s --format=%ct HEAD)
package_date=$(date -u -d "@$source_date_epoch" +%Y%m%d)
package_root="rustsdcmcp_0.1.0-lab.${package_date}.${git_sha12}_amd64"
dist_dir="$repo_root/dist"
archive="$dist_dir/${package_root}.tar.gz"

mkdir -p "$dist_dir"
rm -f -- "$archive" "${archive}.sha256"
artifact_complete=0
build_dir=
cleanup() {
    if [[ -n "$build_dir" ]]; then
        rm -rf -- "$build_dir"
    fi
    if [[ $artifact_complete != 1 ]]; then
        rm -f -- "$archive" "${archive}.sha256"
    fi
}

cargo build --release -p rustsdcmcp --locked

build_dir=$(mktemp -d)
trap cleanup EXIT
stage_dir="$build_dir/$package_root"
mkdir -p "$stage_dir/bin" "$stage_dir/config" "$stage_dir/packaging/lxc" \
    "$stage_dir/packaging/systemd" "$stage_dir/packaging/journald" "$stage_dir/docs"

install -m 0755 target/release/rustsdcmcp "$stage_dir/bin/rustsdcmcp"
# The source example is intentionally retained unchanged; the package carries
# the package-specific state location consumed by its installed service.
sed 's#/var/lib/sdcmcp/changeset-state.json#/var/lib/rustsdcmcp/changeset-state.json#' \
    examples/sdc.example.json >"$stage_dir/config/sdc.json.example"
install -m 0755 packaging/lxc/install.sh "$stage_dir/packaging/lxc/install.sh"
install -m 0644 packaging/systemd/rustsdcmcp.service "$stage_dir/packaging/systemd/rustsdcmcp.service"
install -m 0644 packaging/systemd/rustsdcmcp.sysusers "$stage_dir/packaging/systemd/rustsdcmcp.sysusers"
install -m 0644 packaging/systemd/rustsdcmcp.tmpfiles "$stage_dir/packaging/systemd/rustsdcmcp.tmpfiles"
install -m 0644 packaging/journald/mecmcp.conf "$stage_dir/packaging/journald/mecmcp.conf"
install -m 0644 README.md LICENSE SECURITY.md "$stage_dir/"
install -m 0644 docs/operations.md "$stage_dir/docs/operations.md"

glibc_floor=$(objdump -T "$stage_dir/bin/rustsdcmcp" \
    | { grep -oE 'GLIBC_[0-9]+(\.[0-9]+)+' || true; } \
    | sed 's/GLIBC_//' | sort -Vu | tail -n 1)
[[ -n "$glibc_floor" ]] || {
    printf '%s\n' 'could not determine GLIBC floor' >&2
    exit 1
}
rustc_metadata=$(rustc -vV | tr '\n' ' ' | sed 's/[[:space:]]*$//')
cat >"$stage_dir/BUILD-INFO" <<EOF
release_status=lab-only
version=0.1.0
git_commit=$git_commit
source_date_epoch=$source_date_epoch
target=x86_64-unknown-linux-gnu
mecmcp_ref=changeset-v0.3.6
glibc_floor=$glibc_floor
rustc=$rustc_metadata
EOF

trivy filesystem --scanners vuln --format cyclonedx --output "$stage_dir/SBOM.cdx.json" "$stage_dir"

(
    cd "$build_dir"
    find "$package_root" -print0 | LC_ALL=C sort -z \
        | tar --create --gzip --file="$archive" --format=posix --sort=name \
            --owner=0 --group=0 --numeric-owner \
            --mtime="@$source_date_epoch" \
            --pax-option=delete=atime,delete=ctime --no-recursion \
            --null --files-from=-
)
(
    cd "$dist_dir"
    sha256sum "$(basename -- "$archive")" >"$(basename -- "$archive").sha256"
    sha256sum -c "$(basename -- "$archive").sha256"
)
packaging/tests/package-smoke.sh "$archive"
artifact_complete=1
printf '%s\n' "built $archive"
