//! Credential redaction for tool output.
//!
//! Applied at the MCP tool boundary only, never inside [`crate::SdcClient`],
//! for the reason `projection.rs` gives: change-control reads the same
//! endpoints to capture before-state, and redacting there would hide drift.
//!
//! This is a **denylist**, unlike the certificate allowlists. The families it
//! guards (ICAP servers, v2 sites, device config, image definitions and job status,
//! MNHA sync status, RMA state and reactivation status) are deeply nested and have
//! never been observed on the lab tenant, so there is no observed field set to
//! allowlist. A present-but-redacted marker is used instead of removal so a caller
//! can see the field exists without learning its value.
//!
//! ## Redaction policy
//!
//! `finish_redacted` is used for every read tool, with no per-family
//! exemption. IPS and ECF families previously used plain `finish` on the
//! reasoning that the spec declares no credential fields for them; that
//! reasoning didn't hold up (mecmcp's threat model rates "tool output leaks
//! secrets to the model provider" as unmitigated, T8) because a spec omission
//! is not a guarantee upstream never adds a credential-bearing field, and the
//! denylist below is now wide enough to catch upstream additions (SNMP
//! `community` strings, API tokens, private keys) that a family-by-family
//! carve-out would miss. Every read tool that forwards an upstream SDC
//! response now routes through `finish_redacted`; see `REDACTED_TOOLS` in
//! `tests/tool_contract.rs` for the enforced, exhaustive list.
//!
//! Write tools (`prepare_*`/`apply_*`/`approve_*`/`discard_*`) still call
//! plain `finish`. They don't forward raw upstream SDC responses: they return
//! change-control metadata generated by `self.changes` (digests, change-set
//! status, approval state), not the request or response body being written,
//! so there is no upstream field for the denylist to catch.

use serde_json::Value;

/// Marker substituted for a redacted value.
pub const REDACTED: &str = "[REDACTED]";

/// Keys whose values are credentials, compared case- and separator-insensitively.
///
/// `site_config` and `cpe_config` are not themselves credentials. They are
/// rendered device configuration bodies, and SDC-generated IPsec config carries
/// the IKE pre-shared key, so both are withheld as a whole.
///
/// `private_key` guards certificate private-key fields (see the
/// `injected_private_key_is_dropped_from_local_certificates` test in
/// `projection.rs` for the observed field name); this denylist entry is
/// defence in depth for any endpoint the certificate allowlists don't cover.
///
/// Each key is normalized (lowercased, `_` and `-` removed) before comparison,
/// so `preSharedKey`, `pre_shared_key`, and `PRE-SHARED-KEY` all match.
const SECRET_KEYS: &[&str] = &[
    "password",
    "password_ascii",
    "password_base64",
    "passphrase",
    "psk",
    "pre_shared_key",
    "site_config",
    "cpe_config",
    "secret",
    "token",
    "api_key",
    "private_key",
    "community",
];

/// Base terms that also match as a prefix or suffix of a normalized key, so
/// compound names like `accessToken`, `snmpCommunity`, `communityString`, and
/// `privateKeyPem` are caught even though they never equal an entry in
/// [`SECRET_KEYS`] outright.
///
/// Exact-only matching lets a vendor rename `token` to `accessToken` and slip
/// past the denylist entirely; `psk` is deliberately excluded here since it is
/// short enough that prefix/suffix matching would catch unrelated words.
const COMPOUND_KEY_TERMS: &[&str] = &[
    "token",
    "secret",
    "password",
    "privatekey",
    "community",
    "apikey",
];

/// Normalize a key for comparison: lowercase and remove `_` and `-`.
fn normalize_key(key: &str) -> String {
    key.to_ascii_lowercase()
        .chars()
        .filter(|c| *c != '_' && *c != '-')
        .collect()
}

/// Whether a normalized key is credential-bearing: an exact [`SECRET_KEYS`]
/// match, or a [`COMPOUND_KEY_TERMS`] prefix/suffix match.
fn is_secret_key(normalized: &str) -> bool {
    SECRET_KEYS
        .iter()
        .any(|secret| normalize_key(secret) == normalized)
        || COMPOUND_KEY_TERMS
            .iter()
            .any(|term| normalized.starts_with(term) || normalized.ends_with(term))
}

/// Replace every credential-bearing value in `value`, at any depth.
///
/// `null` stays `null`: it carries no secret, and rewriting it would claim
/// one existed.
#[must_use]
pub fn redact_secrets(mut value: Value) -> Value {
    redact_in_place(&mut value);
    value
}

/// Redact license keys in an RMA state response.
///
/// Replaces each element of the top-level `missing_licenses` array with the
/// REDACTED marker, preserving array length so the count stays visible. The
/// spec describes `missing_licenses` as "Array of license keys that are missing",
/// so the keys are the array VALUES, not object keys.
///
/// Fails closed: if `missing_licenses` is present but not an array (API
/// regression), the entire value is replaced with REDACTED. `null` stays `null`.
///
/// Other fields are left untouched.
#[must_use]
pub fn redact_rma_state(mut value: Value) -> Value {
    if let Some(obj) = value.as_object_mut()
        && let Some(licenses) = obj.get_mut("missing_licenses")
    {
        if let Some(arr) = licenses.as_array_mut() {
            for item in arr.iter_mut() {
                *item = Value::String(REDACTED.to_owned());
            }
        } else if !licenses.is_null() {
            // Fail closed: non-array, non-null → replace wholesale
            *licenses = Value::String(REDACTED.to_owned());
        }
    }
    value
}

fn redact_in_place(value: &mut Value) {
    match value {
        Value::Object(map) => {
            for (key, child) in map.iter_mut() {
                let normalized = normalize_key(key);
                if is_secret_key(&normalized) {
                    if !child.is_null() {
                        *child = Value::String(REDACTED.to_owned());
                    }
                } else {
                    redact_in_place(child);
                }
            }
        }
        Value::Array(items) => items.iter_mut().for_each(redact_in_place),
        _ => {}
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn icap_server_passwords_are_redacted_in_a_list_envelope() {
        let listed = json!({"items": [{
            "uuid": "u1", "name": "icap", "host": "10.0.0.1",
            "password_ascii": "hunter2", "password_base64": "aHVudGVyMg=="
        }], "count": 1});
        let out = redact_secrets(listed);
        assert_eq!(out["items"][0]["password_ascii"], REDACTED);
        assert_eq!(out["items"][0]["password_base64"], REDACTED);
        assert_eq!(out["items"][0]["host"], "10.0.0.1");
        assert_eq!(out["count"], 1);
    }

    #[test]
    fn nested_site_psk_and_config_body_are_redacted() {
        let site = json!({"site": {"site_name": "s1", "cpe_devices": [{
            "name": "cpe",
            "cpe_config": {"body": "...pre-shared-key...", "format": "set"},
            "mist_config": {"pre_shared_key": "k"},
            "cpe_interfaces": [{
                "psk": "shared", "ike_id": "id",
                "site_config": {"body": "set security ike ... pre-shared-key", "format": "set"}
            }]
        }]}});
        let out = redact_secrets(site);
        let device = &out["site"]["cpe_devices"][0];
        assert_eq!(device["cpe_config"], REDACTED);
        assert_eq!(device["mist_config"]["pre_shared_key"], REDACTED);
        let iface = &device["cpe_interfaces"][0];
        assert_eq!(iface["psk"], REDACTED);
        assert_eq!(iface["site_config"], REDACTED);
        assert_eq!(iface["ike_id"], "id");
    }

    #[test]
    fn key_match_is_case_insensitive_and_null_is_left_alone() {
        let out = redact_secrets(json!({"PSK": "x", "password": null}));
        assert_eq!(out["PSK"], REDACTED);
        assert!(out["password"].is_null());
    }

    #[test]
    fn a_value_without_credentials_is_unchanged() {
        let original = json!({"items": [{"name": "a", "keysize": "2048"}]});
        assert_eq!(redact_secrets(original.clone()), original);
    }

    #[test]
    fn camel_case_and_hyphenated_keys_are_redacted() {
        let out = redact_secrets(json!({
            "preSharedKey": "secret1",
            "cpeConfig": {"body": "config"},
            "siteConfig": {"format": "set"},
            "passwordBase64": "c2VjcmV0",
            "keysize": "2048",
            "pskHint": "not-a-secret"
        }));
        assert_eq!(out["preSharedKey"], REDACTED);
        assert_eq!(out["cpeConfig"], REDACTED);
        assert_eq!(out["siteConfig"], REDACTED);
        assert_eq!(out["passwordBase64"], REDACTED);
        // These should NOT be redacted
        assert_eq!(out["keysize"], "2048");
        assert_eq!(out["pskHint"], "not-a-secret");
    }

    #[test]
    fn secret_key_is_redacted() {
        let out = redact_secrets(json!({"secret": "hunter2", "name": "a"}));
        assert_eq!(out["secret"], REDACTED);
        assert_eq!(out["name"], "a");
    }

    #[test]
    fn token_key_is_redacted() {
        let out = redact_secrets(json!({"token": "abc123", "name": "a"}));
        assert_eq!(out["token"], REDACTED);
        assert_eq!(out["name"], "a");
    }

    #[test]
    fn api_key_is_redacted() {
        let out = redact_secrets(json!({"api_key": "abc123", "apiKey": "def456", "name": "a"}));
        assert_eq!(out["api_key"], REDACTED);
        assert_eq!(out["apiKey"], REDACTED);
        assert_eq!(out["name"], "a");
    }

    #[test]
    fn private_key_is_redacted() {
        // A synthetic, non-PEM-shaped placeholder: a real PEM body here trips
        // the full-history Gitleaks scan on every future squash merge (a new
        // commit SHA needs a new `.gitleaksignore` entry each time).
        let out = redact_secrets(json!({
            "private_key": "synthetic-private-key-material",
            "public_key_algorithm": "rsa"
        }));
        assert_eq!(out["private_key"], REDACTED);
        // Public key metadata is not a secret and must survive.
        assert_eq!(out["public_key_algorithm"], "rsa");
    }

    #[test]
    fn community_string_is_redacted() {
        let out = redact_secrets(json!({"community": "public", "name": "a"}));
        assert_eq!(out["community"], REDACTED);
        assert_eq!(out["name"], "a");
    }

    /// Compound key names, which never equal a `SECRET_KEYS` entry exactly,
    /// are still caught by the prefix/suffix match in `is_secret_key`.
    #[test]
    fn compound_credential_key_names_are_redacted() {
        let out = redact_secrets(json!({
            "accessToken": "a",
            "authToken": "b",
            "apiToken": "c",
            "clientSecret": "d",
            "snmpCommunity": "e",
            "communityString": "f",
            "privateKeyPem": "g",
            "current_password": "h",
            "name": "unaffected",
        }));
        for key in [
            "accessToken",
            "authToken",
            "apiToken",
            "clientSecret",
            "snmpCommunity",
            "communityString",
            "privateKeyPem",
            "current_password",
        ] {
            assert_eq!(out[key], REDACTED, "{key} should be redacted");
        }
        assert_eq!(out["name"], "unaffected");
    }

    /// Proves IPS/ECF-shaped output is now redacted. Before this change,
    /// IPS/ECF handlers called plain `finish` and skipped `redact_secrets`
    /// entirely, so an SNMP `community` string on an IPS rule, or a `token`
    /// on an ECF rule set, would have reached the model unredacted.
    #[test]
    fn ips_and_ecf_shaped_responses_are_redacted() {
        let ips_rule = json!({
            "uuid": "r1",
            "name": "block-scan",
            "community": "public",
            "action": "drop"
        });
        let out = redact_secrets(ips_rule);
        assert_eq!(out["community"], REDACTED);
        assert_eq!(out["action"], "drop");

        let ecf_rule_set = json!({
            "items": [{"uuid": "s1", "name": "blocklist", "token": "ecf-abc123"}],
            "count": 1
        });
        let out = redact_secrets(ecf_rule_set);
        assert_eq!(out["items"][0]["token"], REDACTED);
        assert_eq!(out["items"][0]["name"], "blocklist");
        assert_eq!(out["count"], 1);
    }

    #[test]
    fn rma_state_missing_licenses_are_redacted() {
        let state = json!({
            "device_id": "dev1",
            "rma_state": "ACTIVE",
            "missing_licenses": ["LIC-KEY-123", "LIC-KEY-456", "LIC-KEY-789"],
            "other_field": "untouched"
        });
        let out = redact_rma_state(state);
        assert_eq!(
            out["missing_licenses"]
                .as_array()
                .expect("missing_licenses should be an array")
                .len(),
            3
        );
        assert_eq!(out["missing_licenses"][0], REDACTED);
        assert_eq!(out["missing_licenses"][1], REDACTED);
        assert_eq!(out["missing_licenses"][2], REDACTED);
        assert_eq!(out["device_id"], "dev1");
        assert_eq!(out["other_field"], "untouched");
    }

    #[test]
    fn rma_state_without_missing_licenses_is_unchanged() {
        let state = json!({"device_id": "dev1", "rma_state": "ACTIVE"});
        let out = redact_rma_state(state.clone());
        assert_eq!(out, state);
    }

    #[test]
    fn rma_state_empty_missing_licenses_stays_empty() {
        let state = json!({"missing_licenses": []});
        let out = redact_rma_state(state);
        assert_eq!(
            out["missing_licenses"]
                .as_array()
                .expect("missing_licenses should be an array")
                .len(),
            0
        );
    }

    #[test]
    fn rma_state_non_array_missing_licenses_is_redacted() {
        // Fail closed: if missing_licenses is a string (API regression), redact it
        let state = json!({"device_id": "dev1", "missing_licenses": "LIC-KEY-MALFORMED"});
        let out = redact_rma_state(state);
        assert_eq!(out["missing_licenses"], REDACTED);
        assert_eq!(out["device_id"], "dev1");
    }

    #[test]
    fn rma_state_null_missing_licenses_stays_null() {
        // null carries no secret, so leave it alone
        let state = json!({"device_id": "dev1", "missing_licenses": null});
        let out = redact_rma_state(state);
        assert!(out["missing_licenses"].is_null());
        assert_eq!(out["device_id"], "dev1");
    }
}
